server:
  port: 8083
spring:
  rabbitmq:
    host: 192.168.146.134
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:mysql://192.168.146.142:3306/ms_user?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: yyx-ms-user
  cloud:
    consul:
      discovery:
        tags: jifang=nanjing
        prefer-ip-address: true   #显示主机ip地址
        #注册到consul上的实例名称
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}
        #instance-id: ${spring.application.name}-${server.port}-${spring.cloud.client.hostname}

        # prefer-agent-address: true
    stream:
      bindings:
        input:
          destination: stream-test
          #相同实例下 相同group 只有一个实例消费 收到的信息
          #负载均衡 轮询算法
          group: g1
        myInput:
          destination: stream-mytest
  #    inetutils:
#      preferred-networks:
#       # - 183.67.53.178
#        - 183.67
#        - 192.168    #指定显示的ip
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


---
spring:
  profiles: dev
testProfile: dev
---
spring:
  profiles: prod
testProfile: prod